# Docs for the Azure Functions Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure:       https://github.com/Azure/actions

name: Build and deploy Node.js project to Azure Function App - livekit-agent-azure-func

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src'   # publicamos todo src/ como wwwroot
  NODE_VERSION: '20.x'                    # Node version

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install, Prisma & Build
        shell: pwsh
        run: |
          pushd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

          # 1️⃣ Instala dependencias
          npm install

          # 2️⃣ Genera Prisma Client
          npm run prisma:generate

          # 3️⃣ Aplica migraciones
          npm run migrate:deploy

          # 4️⃣ Compila TS → JS
          npm run build

          popd

      - name: Upload artifact for deploy
        uses: actions/upload-artifact@v4
        with:
          name: functionapp-src
          path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: functionapp-src
          path: functionapp-src

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZUREAPPSERVICE_CLIENTID_B9CC5E7DD4CD4EBF84F817C7243AC885 }}
          tenant-id:       ${{ secrets.AZUREAPPSERVICE_TENANTID_47BEC7C0624B42299932C78F6C01DF57 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_80E5F5856F2F46CFB7B591B7CD076727 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name:  'livekit-agent-azure-func'
          slot-name: 'Production'
          package:   '${{ github.workspace }}/functionapp-src'
          enable-oryx-build: true
          respect-funcignore: true
