name: Build and deploy – livekit-agent-azure-func

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FUNC_SRC: src
  NODE_VER: '20.x'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VER }}

      - name: Install, build & Prisma
        shell: pwsh
        run: |
          pushd ${{ env.FUNC_SRC }}
          npm install
          npm run build
          npm run prisma:generate
          if (-Not (Test-Path ".\node_modules\.prisma\client")) {
            Write-Error "❌ No se generó Prisma Client"
            exit 1
          }
          npm run migrate:deploy
          popd

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: functionapp-src
          path: ${{ env.FUNC_SRC }}
          include-hidden-files: true
          if-no-files-found: error

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: functionapp-src
          path: functionapp-src

      - name: Verify Prisma in artifact
        shell: pwsh
        run: |
          if (-Not (Test-Path "functionapp-src\node_modules\.prisma\client")) {
            Write-Error "❌ Prisma Client no viajó en el artifact"
            exit 1
          }

      - name: Login to Azure
        uses: azure/login@v2
        with:                            # ← debe ir aquí, no bajo 'env'
          client-id:       ${{ secrets.AZUREAPPSERVICE_CLIENTID_B9CC5E7DD4CD4EBF84F817C7243AC885 }}
          tenant-id:       ${{ secrets.AZUREAPPSERVICE_TENANTID_47BEC7C0624B42299932C78F6C01DF57 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_80E5F5856F2F46CFB7B591B7CD076727 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name:                       livekit-agent-azure-func
          slot-name:                      Production
          package:                        '${{ github.workspace }}/functionapp-src'
          scm-do-build-during-deployment: false
          respect-funcignore:             true
